/**
 * Script to generate a story registry from Storybook story files.
 * Scans packages/registry/ui/*.stories.tsx and generates a static import map
 * that the docs site can use to render story previews.
 *
 * Run this before building the docs site (included in prebuild).
 */

import fs from 'fs';
import path from 'path';

const REGISTRY_PATH = path.join(__dirname, '..', '..', 'packages', 'registry', 'ui');
const OUTPUT_PATH = path.join(__dirname, '..', 'src', 'lib', 'story-registry.ts');

function extractExportNames(filePath: string): string[] {
  const content = fs.readFileSync(filePath, 'utf-8');
  const exports: string[] = [];

  // Match: export const Name = {
  const constExports = content.matchAll(/export\s+(?:const|let|var)\s+(\w+)\s*=/g);
  for (const match of constExports) {
    const name = match[1];
    // Skip 'default' and the meta export
    if (name !== 'default') {
      exports.push(name);
    }
  }

  // Match: export function Name
  const fnExports = content.matchAll(/export\s+function\s+(\w+)/g);
  for (const match of fnExports) {
    exports.push(match[1]);
  }

  return exports;
}

function main() {
  // Find all story files
  const storyFiles = fs.readdirSync(REGISTRY_PATH)
    .filter(f => f.endsWith('.stories.tsx'))
    .sort();

  if (storyFiles.length === 0) {
    console.log('No story files found, generating empty registry.');
    fs.writeFileSync(OUTPUT_PATH, `// Auto-generated - do not edit
export const storyRegistry: Record<string, any> = {};

export function getStory(_componentName: string, _storyName: string) {
  return null;
}
`);
    return;
  }

  const imports: string[] = [];
  const registryEntries: string[] = [];

  for (const file of storyFiles) {
    const componentName = file.replace('.stories.tsx', '');
    const filePath = path.join(REGISTRY_PATH, file);
    const exportNames = extractExportNames(filePath);

    if (exportNames.length === 0) continue;

    // Generate import alias prefix from component name (e.g., 'button' -> 'button', 'calendar-input' -> 'calendarInput')
    const prefix = componentName.replace(/-([a-z])/g, (_, c) => c.toUpperCase());

    // Import default (meta) and named exports
    const namedImports = exportNames.map(name => `${name} as ${prefix}_${name}`).join(', ');
    imports.push(`import { default as ${prefix}Meta, ${namedImports} } from '@/components/ui/${componentName}.stories';`);

    // Build stories object
    const storiesObj = exportNames.map(name => `    '${name}': ${prefix}_${name}`).join(',\n');
    registryEntries.push(`  '${componentName}': {\n    meta: ${prefix}Meta,\n    stories: {\n${storiesObj}\n    }\n  }`);
  }

  const output = `// Auto-generated by generate-story-registry.ts - do not edit
'use client';

${imports.join('\n')}

export const storyRegistry: Record<string, {
  meta: any;
  stories: Record<string, any>;
}> = {
${registryEntries.join(',\n')}
};

export function getStory(componentName: string, storyName: string): (() => React.ReactNode) | null {
  const mod = storyRegistry[componentName];
  if (!mod) return null;
  const story = mod.stories[storyName];
  if (!story) return null;
  return typeof story === 'function' ? story : story.render ?? null;
}
`;

  fs.writeFileSync(OUTPUT_PATH, output);
  console.log(`✓ Generated story registry with ${storyFiles.length} components`);
  console.log(`  Stories: ${storyFiles.map(f => f.replace('.stories.tsx', '')).join(', ')}`);
  console.log(`  Output: ${OUTPUT_PATH}`);
}

main();
