/**
 * Generates the two static Tailwind v3 token files from one source.
 *
 * Source of truth: packages/cli/src/utils/templates/tokens.ts
 *
 * Generated from it:
 *   packages/registry/styles/happly-ui-tailwind.cjs
 *     Tailwind plugin. Fetched at runtime by the CLI during `init` for v3
 *     projects, so pushing token changes to `production` makes them available
 *     immediately without a CLI republish.
 *   tailwind-manual-installation/v3/happly-tailwind.preset.js
 *     Tailwind preset for the manual-install path documented in README.md.
 *     Self-contained on purpose: a user copies this one file next to their
 *     tailwind.config.js and it resolves offline, with no reference back to
 *     the registry.
 *
 * Runs as part of `bun run build:registry`. Run it on its own with
 * `bun run scripts/build-tailwind-plugin.ts`.
 */

import fs from 'fs';
import path from 'path';
import prettier from 'prettier';

// Import tokens from the CLI templates (source of truth)
import {
  texts,
  shadows,
  dropShadows,
  borderRadii,
  colors,
  fontFamilies,
  backgroundImage,
  screens,
  keyframes,
  animations,
} from '../packages/cli/src/utils/templates/tokens.js';

const root = path.join(__dirname, '..');

const PLUGIN_PATH = path.join(
  root,
  'packages',
  'registry',
  'styles',
  'happly-ui-tailwind.cjs'
);

const PRESET_PATH = path.join(
  root,
  'tailwind-manual-installation',
  'v3',
  'happly-tailwind.preset.js'
);

const themeExtend = {
  colors,
  fontSize: texts,
  boxShadow: shadows,
  dropShadow: dropShadows,
  borderRadius: borderRadii,
  fontFamily: fontFamilies,
  backgroundImage,
  screens,
  keyframes,
  animation: animations,
};

const config = { theme: { extend: themeExtend } };

// --- Registry plugin (fetched by the CLI, written verbatim into projects) ---

const pluginContent = `// HapplyUI Design Tokens — https://ui.happly.cloud
// Auto-generated by build-tailwind-plugin.ts — do not edit manually
// This plugin extends your Tailwind config with HapplyUI design tokens.
// It uses Tailwind's plugin API for proper deep-merging with your existing config.

const plugin = require('tailwindcss/plugin');

module.exports = plugin(function() {
  // No base styles needed — CSS variables are in happly-theme.css
}, ${JSON.stringify(config, null, 2)});
`;

// --- Manual-install preset -------------------------------------------------

// `tailwindcss-animate` is registered here so the copied preset is complete on
// its own: the overlay components (modal, drawer, popover, tooltip, dropdown,
// select) emit nothing without its animate-in/out utilities. The v4 theme CSS
// registers it with `@plugin`, and the CLI adds it to the config for v3.
const presetContent = `/**
 * HapplyUI Design Tokens — https://ui.happly.cloud
 *
 * Tailwind v3 preset for the manual installation path. Auto-generated by
 * scripts/build-tailwind-plugin.ts from packages/cli/src/utils/templates/tokens.ts
 * — do not edit manually. Regenerate with \`bun run build:registry\`.
 *
 * Pair it with tailwind-manual-installation/v3/globals.css, which defines the
 * CSS custom properties these tokens read.
 */

/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: { extend: ${JSON.stringify(themeExtend, null, 2)} },
  plugins: [require('tailwindcss-animate')],
};
`;

// The preset is a file users copy into their own project and read, so it is
// emitted through Prettier with the repo's own config rather than as raw
// JSON.stringify output.
const presetFormatted = await prettier.format(presetContent, {
  ...(await prettier.resolveConfig(PRESET_PATH)),
  filepath: PRESET_PATH,
});

fs.writeFileSync(PLUGIN_PATH, pluginContent);
console.log(`✓ Generated Tailwind plugin at ${PLUGIN_PATH}`);

fs.writeFileSync(PRESET_PATH, presetFormatted);
console.log(`✓ Generated Tailwind preset at ${PRESET_PATH}`);
