/**
 * Generates the static happly-ui-tailwind.cjs plugin file in the registry.
 *
 * This file is fetched at runtime by the CLI during `init` for v3 projects,
 * so pushing token changes to `production` makes them available immediately
 * without a CLI republish.
 *
 * Usage: bun run scripts/build-tailwind-plugin.ts
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Import tokens from the CLI templates (source of truth)
import {
  texts,
  shadows,
  borderRadii,
  colors,
  fontFamilies,
  backgroundImage,
  screens,
  keyframes,
  animations,
} from '../packages/cli/src/utils/templates/tokens.js';

const OUTPUT_PATH = path.join(
  __dirname,
  '..',
  'packages',
  'registry',
  'styles',
  'happly-ui-tailwind.cjs'
);

const config = {
  theme: {
    extend: {
      colors,
      fontSize: texts,
      boxShadow: shadows,
      borderRadius: borderRadii,
      fontFamily: fontFamilies,
      backgroundImage,
      screens,
      keyframes,
      animation: animations,
    },
  },
};

const content = `// HapplyUI Design Tokens — https://ui.happly.cloud
// Auto-generated by build-tailwind-plugin.ts — do not edit manually
// This plugin extends your Tailwind config with HapplyUI design tokens.
// It uses Tailwind's plugin API for proper deep-merging with your existing config.

const plugin = require('tailwindcss/plugin');

module.exports = plugin(function() {
  // No base styles needed — CSS variables are in happly-theme.css
}, ${JSON.stringify(config, null, 2)});
`;

fs.writeFileSync(OUTPUT_PATH, content);
console.log(`✓ Generated Tailwind plugin at ${OUTPUT_PATH}`);
