import { readFile, writeFile } from 'fs/promises';
import path from 'path';
import { existsSync } from 'fs';
import {
  texts,
  shadows,
  borderRadii,
  colors,
  fontFamilies,
  backgroundImage,
  screens,
  keyframes,
  animations,
} from '../templates/tokens.js';
import type { HapplyConfig } from '../../types/index.js';
import { logger } from '../logger.js';

const HAPPLY_PLUGIN_FILE = 'happly-ui-tailwind.cjs';

/**
 * Update Tailwind configuration based on version.
 *
 * For v4: tokens live in happly-theme.css (written by init). Nothing to do here.
 * For v3: write a Tailwind plugin with design tokens and register it.
 */
export async function updateTailwindConfig(
  cwd: string,
  config: HapplyConfig,
  tailwindVersion: number
): Promise<void> {
  if (tailwindVersion === 4) {
    logger.success('Happly tokens applied via happly-theme.css (v4)');
  } else {
    await updateConfigV3(cwd, config);
  }
}

/**
 * Update Tailwind Config for v3.
 *
 * Writes a plugin file (happly-ui-tailwind.cjs) that extends the Tailwind
 * theme with HapplyUI design tokens. Uses Tailwind's plugin API so that
 * colors are deep-merged with the user's existing config (including shadcn).
 *
 * Then registers the plugin in tailwind.config.ts plugins array.
 */
async function updateConfigV3(
  cwd: string,
  config: HapplyConfig
): Promise<void> {
  const configPath = path.join(cwd, config.tailwind.config);
  if (!existsSync(configPath)) {
    logger.warn(`Tailwind config file not found at ${configPath}`);
    return;
  }

  // Write the plugin file
  const pluginPath = path.join(cwd, HAPPLY_PLUGIN_FILE);
  const pluginContent = generatePluginFile();

  if (existsSync(pluginPath)) {
    logger.info(`Overwriting existing ${HAPPLY_PLUGIN_FILE}`);
  }
  await writeFile(pluginPath, pluginContent, 'utf-8');
  logger.success(`Created ${HAPPLY_PLUGIN_FILE}`);

  // Register plugin in tailwind config
  let content = await readFile(configPath, 'utf-8');

  if (content.includes(HAPPLY_PLUGIN_FILE)) {
    logger.info(`${HAPPLY_PLUGIN_FILE} already registered in tailwind config.`);
    return;
  }

  const pluginsRegex = /plugins:\s*\[/;
  if (pluginsRegex.test(content)) {
    content = content.replace(
      pluginsRegex,
      (match) => `${match}\n    require('./${HAPPLY_PLUGIN_FILE}'),`
    );
    await writeFile(configPath, content, 'utf-8');
    logger.success(
      `Registered ${HAPPLY_PLUGIN_FILE} in ${config.tailwind.config}`
    );
  } else {
    // No plugins array — try to add one before the closing brace of the config
    const closingBrace = /}\s*;?\s*$/;
    if (closingBrace.test(content)) {
      content = content.replace(
        closingBrace,
        `  plugins: [require('./${HAPPLY_PLUGIN_FILE}')],\n};`
      );
      await writeFile(configPath, content, 'utf-8');
      logger.success(
        `Added plugins array with ${HAPPLY_PLUGIN_FILE} to ${config.tailwind.config}`
      );
    } else {
      logger.warn(
        `Could not update ${config.tailwind.config}. Add manually:\n` +
          `  plugins: [require('./${HAPPLY_PLUGIN_FILE}')]`
      );
    }
  }
}

/**
 * Generate the HapplyUI Tailwind plugin file content.
 *
 * This plugin extends the theme with all design tokens.
 * Using Tailwind's plugin API ensures proper deep-merging with
 * existing user config (shadcn primary, etc.) without key conflicts.
 */
function generatePluginFile(): string {
  const config = {
    theme: {
      extend: {
        colors: colors,
        fontSize: texts,
        boxShadow: shadows,
        borderRadius: borderRadii,
        fontFamily: fontFamilies,
        backgroundImage: backgroundImage,
        screens: screens,
        keyframes: keyframes,
        animation: animations,
      },
    },
  };

  return `// HapplyUI Design Tokens — https://ui.happly.cloud
// Auto-generated by @happlyui/cli — do not edit manually
// This plugin extends your Tailwind config with HapplyUI design tokens.
// It uses Tailwind's plugin API for proper deep-merging with your existing config.

const plugin = require('tailwindcss/plugin');

module.exports = plugin(function() {
  // No base styles needed — CSS variables are in happly-theme.css
}, ${JSON.stringify(config, null, 2)});
`;
}
