// Auto-generated by generate-story-registry.ts - do not edit
'use client';

import { default as alertMeta, Playground as alert_Playground, Filled as alert_Filled, Light as alert_Light, Lighter as alert_Lighter, Stroke as alert_Stroke, XSmall as alert_XSmall, Small as alert_Small, Large as alert_Large } from '@/components/ui/alert.stories';
import { default as avatarGroupCompactMeta, Playground as avatarGroupCompact_Playground, Default as avatarGroupCompact_Default, Size as avatarGroupCompact_Size } from '@/components/ui/avatar-group-compact.stories';
import { default as avatarGroupMeta, Playground as avatarGroup_Playground, Size as avatarGroup_Size } from '@/components/ui/avatar-group.stories';
import { default as avatarMeta, Playground as avatar_Playground, Color as avatar_Color, Size as avatar_Size, Text as avatar_Text, Placeholder as avatar_Placeholder, Status as avatar_Status, Notification as avatar_Notification, BrandLogo as avatar_BrandLogo, IndicatorCustomSVG as avatar_IndicatorCustomSVG, AsLink as avatar_AsLink } from '@/components/ui/avatar.stories';
import { default as badgeMeta, Playground as badge_Playground, BadgeFilled as badge_BadgeFilled, BadgeLight as badge_BadgeLight, BadgeLighter as badge_BadgeLighter, BadgeStroke as badge_BadgeStroke, BadgeColors as badge_BadgeColors, Size as badge_Size, Square as badge_Square, WithIcon as badge_WithIcon, WithDot as badge_WithDot, Disabled as badge_Disabled, AsChild as badge_AsChild } from '@/components/ui/badge.stories';
import { default as bannerMeta, Playground as banner_Playground, Error as banner_Error, Warning as banner_Warning, Success as banner_Success, Information as banner_Information, Feature as banner_Feature, Primary as banner_Primary } from '@/components/ui/banner.stories';
import { default as buttonGroupMeta, Playground as buttonGroup_Playground, Default as buttonGroup_Default, Sizes as buttonGroup_Sizes } from '@/components/ui/button-group.stories';
import { default as buttonMeta, Playground as button_Playground, PrimaryVariant as button_PrimaryVariant, NeutralVariant as button_NeutralVariant, SuccessVariant as button_SuccessVariant, WarningVariant as button_WarningVariant, ErrorVariant as button_ErrorVariant, Sizes as button_Sizes, Disabled as button_Disabled, WithIcon as button_WithIcon, FullWidth as button_FullWidth, AsChild as button_AsChild, Composition as button_Composition } from '@/components/ui/button.stories';
import { default as checkboxMeta, Playground as checkbox_Playground, Demo as checkbox_Demo, Variants as checkbox_Variants, Disabled as checkbox_Disabled, WithLabel as checkbox_WithLabel, WithLabelExtended as checkbox_WithLabelExtended } from '@/components/ui/checkbox.stories';
import { default as colorPickerMeta, Playground as colorPicker_Playground, Demo as colorPicker_Demo, PopoverDemo as colorPicker_PopoverDemo } from '@/components/ui/color-picker.stories';
import { default as comboBoxMeta, Playground as comboBox_Playground, Default as comboBox_Default, WithPreselectedValues as comboBox_WithPreselectedValues, Uncontrolled as comboBox_Uncontrolled, FormSubmission as comboBox_FormSubmission, Sizes as comboBox_Sizes, SelectionConstraints as comboBox_SelectionConstraints, TagVariants as comboBox_TagVariants, States as comboBox_States, Customization as comboBox_Customization, WithIcons as comboBox_WithIcons } from '@/components/ui/combo-box.stories';
import { default as commandMenuMeta, Playground as commandMenu_Playground, Demo as commandMenu_Demo } from '@/components/ui/command-menu.stories';
import { default as compactButtonMeta, Playground as compactButton_Playground, Stroke as compactButton_Stroke, Ghost as compactButton_Ghost, White as compactButton_White, Modifiable as compactButton_Modifiable, Sizes as compactButton_Sizes, FullRadius as compactButton_FullRadius, Disabled as compactButton_Disabled, AsChild as compactButton_AsChild } from '@/components/ui/compact-button.stories';
import { default as currencyInputMeta, Playground as currencyInput_Playground, Default as currencyInput_Default, Controlled as currencyInput_Controlled, Sizes as currencyInput_Sizes, ErrorState as currencyInput_ErrorState } from '@/components/ui/currency-input.stories';
import { default as datepickerMeta, Playground as datepicker_Playground, Demo as datepicker_Demo, PopoverDemo as datepicker_PopoverDemo, ApprovalDemo as datepicker_ApprovalDemo, RangeDemo as datepicker_RangeDemo } from '@/components/ui/datepicker.stories';
import { default as digitInputMeta, Playground as digitInput_Playground, Demo as digitInput_Demo, HasError as digitInput_HasError, Disabled as digitInput_Disabled, Square as digitInput_Square } from '@/components/ui/digit-input.stories';
import { default as dividerMeta, Playground as divider_Playground, Line as divider_Line, LineSpacing as divider_LineSpacing, LineText as divider_LineText, TextOnly as divider_TextOnly, SolidText as divider_SolidText, Content as divider_Content } from '@/components/ui/divider.stories';
import { default as dotStepperMeta, Playground as dotStepper_Playground, Demo as dotStepper_Demo, WithRadixTabs as dotStepper_WithRadixTabs } from '@/components/ui/dot-stepper.stories';
import { default as drawerMeta, Playground as drawer_Playground, Demo as drawer_Demo, Basic as drawer_Basic } from '@/components/ui/drawer.stories';
import { default as dropdownMeta, Playground as dropdown_Playground, Demo as dropdown_Demo, SubMenu as dropdown_SubMenu } from '@/components/ui/dropdown.stories';
import { default as emojiDialogMeta, Playground as emojiDialog_Playground, Default as emojiDialog_Default, DeleteConfirmation as emojiDialog_DeleteConfirmation, UnsavedChanges as emojiDialog_UnsavedChanges, SuccessConfirmation as emojiDialog_SuccessConfirmation, WithFormContent as emojiDialog_WithFormContent, WithFloatingMemojis as emojiDialog_WithFloatingMemojis, StaticNoAnimations as emojiDialog_StaticNoAnimations, CustomEmojiArea as emojiDialog_CustomEmojiArea } from '@/components/ui/emoji-dialog.stories';
import { default as fancyButtonMeta, Playground as fancyButton_Playground, Neutral as fancyButton_Neutral, Primary as fancyButton_Primary, Error as fancyButton_Error, Basic as fancyButton_Basic, WithIcon as fancyButton_WithIcon, Sizes as fancyButton_Sizes, Disabled as fancyButton_Disabled, AsChild as fancyButton_AsChild } from '@/components/ui/fancy-button.stories';
import { default as fileFormatIconMeta, Default as fileFormatIcon_Default, Colors as fileFormatIcon_Colors, Sizes as fileFormatIcon_Sizes } from '@/components/ui/file-format-icon.stories';
import { default as fileUploadCardMeta, Uploading as fileUploadCard_Uploading, Failed as fileUploadCard_Failed, CompletedDocument as fileUploadCard_CompletedDocument, CompletedImage as fileUploadCard_CompletedImage, CompletedVideo as fileUploadCard_CompletedVideo, CompletedAudio as fileUploadCard_CompletedAudio, CompactUploading as fileUploadCard_CompactUploading, CompactCompleted as fileUploadCard_CompactCompleted, CompactFailed as fileUploadCard_CompactFailed, ItemUploading as fileUploadCard_ItemUploading, ItemFailed as fileUploadCard_ItemFailed, ItemCompletedDocument as fileUploadCard_ItemCompletedDocument, ItemCompletedImage as fileUploadCard_ItemCompletedImage, ItemCompactUploading as fileUploadCard_ItemCompactUploading, ItemCompactCompleted as fileUploadCard_ItemCompactCompleted, ItemCompactFailed as fileUploadCard_ItemCompactFailed } from '@/components/ui/file-upload-card.stories';
import { default as fileUploadMeta, Document as fileUpload_Document, Image as fileUpload_Image, Video as fileUpload_Video, Audio as fileUpload_Audio, Attachment as fileUpload_Attachment, CustomOverrides as fileUpload_CustomOverrides, Dragging as fileUpload_Dragging } from '@/components/ui/file-upload.stories';
import { default as formFieldMeta, Playground as formField_Playground, Demo as formField_Demo } from '@/components/ui/form-field.stories';
import { default as hintMeta, Playground as hint_Playground, Demo as hint_Demo, Disabled as hint_Disabled, HasError as hint_HasError } from '@/components/ui/hint.stories';
import { default as inputMeta, Playground as input_Playground, WithIcon as input_WithIcon, Sizes as input_Sizes, WithAffix as input_WithAffix, WithInlineAffix as input_WithInlineAffix, LabelAndHint as input_LabelAndHint, WithKbd as input_WithKbd, Password as input_Password, PasswordWithLevel as input_PasswordWithLevel, Disabled as input_Disabled, ErrorState as input_ErrorState, WithButton as input_WithButton, WithTags as input_WithTags, DateFieldStory as input_DateFieldStory, PaymentInput as input_PaymentInput, WithSelect as input_WithSelect, WithInlineSelect as input_WithInlineSelect, CounterInput as input_CounterInput, Composition as input_Composition } from '@/components/ui/input.stories';
import { default as kbdMeta, Playground as kbd_Playground, Demo as kbd_Demo } from '@/components/ui/kbd.stories';
import { default as keyIconMeta, Playground as keyIcon_Playground, Stroke as keyIcon_Stroke, Lighter as keyIcon_Lighter, Sizes as keyIcon_Sizes, Colors as keyIcon_Colors } from '@/components/ui/key-icon.stories';
import { default as labelMeta, Playground as label_Playground, Demo as label_Demo } from '@/components/ui/label.stories';
import { default as levelBarMeta, Playground as levelBar_Playground, Levels as levelBar_Levels, CustomSegments as levelBar_CustomSegments } from '@/components/ui/level-bar.stories';
import { default as linkButtonMeta, Playground as linkButton_Playground, Gray as linkButton_Gray, Black as linkButton_Black, Primary as linkButton_Primary, Error as linkButton_Error, Modifiable as linkButton_Modifiable, Sizes as linkButton_Sizes, Underline as linkButton_Underline, WithIcon as linkButton_WithIcon, Disabled as linkButton_Disabled, AsChild as linkButton_AsChild } from '@/components/ui/link-button.stories';
import { default as locationInputMeta, Playground as locationInput_Playground, Default as locationInput_Default } from '@/components/ui/location-input.stories';
import { default as modalMeta, Playground as modal_Playground, Demo as modal_Demo, WithHeader as modal_WithHeader } from '@/components/ui/modal.stories';
import { default as paginationMeta, Playground as pagination_Playground, Demo as pagination_Demo, Rounded as pagination_Rounded, Group as pagination_Group, AsLink as pagination_AsLink } from '@/components/ui/pagination.stories';
import { default as passwordInputMeta, Playground as passwordInput_Playground, Default as passwordInput_Default, WithStrength as passwordInput_WithStrength, Sizes as passwordInput_Sizes, ErrorState as passwordInput_ErrorState } from '@/components/ui/password-input.stories';
import { default as phoneInputMeta, Playground as phoneInput_Playground, Default as phoneInput_Default } from '@/components/ui/phone-input.stories';
import { default as popoverMeta, Playground as popover_Playground, Demo as popover_Demo, Position as popover_Position } from '@/components/ui/popover.stories';
import { default as progressBarMeta, Playground as progressBar_Playground, Color as progressBar_Color, WithLabel as progressBar_WithLabel, DataStorage as progressBar_DataStorage } from '@/components/ui/progress-bar.stories';
import { default as progressCircleMeta, Playground as progressCircle_Playground, Default as progressCircle_Default } from '@/components/ui/progress-circle.stories';
import { default as radioCardMeta, Playground as radioCard_Playground, Default as radioCard_Default, WithKeyIcons as radioCard_WithKeyIcons, WithSimpleIcons as radioCard_WithSimpleIcons, WithBadges as radioCard_WithBadges, InlineDescription as radioCard_InlineDescription, AllowDeselect as radioCard_AllowDeselect, Disabled as radioCard_Disabled, ErrorState as radioCard_ErrorState, Composed as radioCard_Composed, PrimaryVariant as radioCard_PrimaryVariant } from '@/components/ui/radio-card.stories';
import { default as radioMeta, Playground as radio_Playground, Demo as radio_Demo, Variants as radio_Variants, Disabled as radio_Disabled, WithLabel as radio_WithLabel, WithLabelExtended as radio_WithLabelExtended } from '@/components/ui/radio.stories';
import { default as sectionToggleMeta, Playground as sectionToggle_Playground, Default as sectionToggle_Default, Collapsed as sectionToggle_Collapsed, Composed as sectionToggle_Composed } from '@/components/ui/section-toggle.stories';
import { default as sectionMeta, Playground as section_Playground, Default as section_Default, WithCustomHeaderWidth as section_WithCustomHeaderWidth, Composed as section_Composed } from '@/components/ui/section.stories';
import { default as selectMeta, Playground as select_Playground, Demo as select_Demo, WithLabelHint as select_WithLabelHint, WithIcons as select_WithIcons, Sizes as select_Sizes, WithCountryFlags as select_WithCountryFlags, WithUsers as select_WithUsers, Disabled as select_Disabled, Compact as select_Compact, CompactCountry as select_CompactCountry, CompactSizes as select_CompactSizes, InlineCountry as select_InlineCountry, InputWithInlineSelect as select_InputWithInlineSelect, WithInput as select_WithInput, WithInputSizes as select_WithInputSizes } from '@/components/ui/select.stories';
import { default as sliderMeta, Playground as slider_Playground, Demo as slider_Demo, Variants as slider_Variants, Range as slider_Range, WithTooltip as slider_WithTooltip } from '@/components/ui/slider.stories';
import { default as socialsInputMeta, Playground as socialsInput_Playground, Default as socialsInput_Default } from '@/components/ui/socials-input.stories';
import { default as statusBadgeMeta, Playground as statusBadge_Playground, Disabled as statusBadge_Disabled, Completed as statusBadge_Completed, Failed as statusBadge_Failed, Pending as statusBadge_Pending, AsChild as statusBadge_AsChild } from '@/components/ui/status-badge.stories';
import { default as switchMeta, Playground as switch_Playground, Demo as switch_Demo, Variants as switch_Variants, Disabled as switch_Disabled, WithLabel as switch_WithLabel, WithLabelExtended as switch_WithLabelExtended } from '@/components/ui/switch.stories';
import { default as tableMeta, Default as table_Default } from '@/components/ui/table.stories';
import { default as tagInputMeta, Playground as tagInput_Playground, Default as tagInput_Default, Controlled as tagInput_Controlled, MaxTags as tagInput_MaxTags, GrayVariant as tagInput_GrayVariant, Sizes as tagInput_Sizes } from '@/components/ui/tag-input.stories';
import { default as tagMeta, Playground as tag_Playground, Stroke as tag_Stroke, Gray as tag_Gray, Rounded as tag_Rounded, Disabled as tag_Disabled, WithImage as tag_WithImage, WithAvatar as tag_WithAvatar, Dismissable as tag_Dismissable } from '@/components/ui/tag.stories';
import { default as textareaMeta, Playground as textarea_Playground, Demo as textarea_Demo, InteractiveCounter as textarea_InteractiveCounter, HasError as textarea_HasError, WithLabelAndHint as textarea_WithLabelAndHint, Disabled as textarea_Disabled, Simple as textarea_Simple, SimpleResize as textarea_SimpleResize } from '@/components/ui/textarea.stories';
import { default as themeProviderMeta, Default as themeProvider_Default, Global as themeProvider_Global, MultipleThemes as themeProvider_MultipleThemes } from '@/components/ui/theme-provider.stories';
import { default as tooltipMeta, Playground as tooltip_Playground, Light as tooltip_Light, Size as tooltip_Size, Position as tooltip_Position, HTMLContent as tooltip_HTMLContent } from '@/components/ui/tooltip.stories';
import { default as uploadFileInputMeta, Playground as uploadFileInput_Playground, Showcase as uploadFileInput_Showcase } from '@/components/ui/upload-file-input.stories';

export const storyRegistry: Record<string, {
  meta: any;
  stories: Record<string, any>;
}> = {
  'alert': {
    meta: alertMeta,
    stories: {
    'Playground': alert_Playground,
    'Filled': alert_Filled,
    'Light': alert_Light,
    'Lighter': alert_Lighter,
    'Stroke': alert_Stroke,
    'XSmall': alert_XSmall,
    'Small': alert_Small,
    'Large': alert_Large
    }
  },
  'avatar-group-compact': {
    meta: avatarGroupCompactMeta,
    stories: {
    'Playground': avatarGroupCompact_Playground,
    'Default': avatarGroupCompact_Default,
    'Size': avatarGroupCompact_Size
    }
  },
  'avatar-group': {
    meta: avatarGroupMeta,
    stories: {
    'Playground': avatarGroup_Playground,
    'Size': avatarGroup_Size
    }
  },
  'avatar': {
    meta: avatarMeta,
    stories: {
    'Playground': avatar_Playground,
    'Color': avatar_Color,
    'Size': avatar_Size,
    'Text': avatar_Text,
    'Placeholder': avatar_Placeholder,
    'Status': avatar_Status,
    'Notification': avatar_Notification,
    'BrandLogo': avatar_BrandLogo,
    'IndicatorCustomSVG': avatar_IndicatorCustomSVG,
    'AsLink': avatar_AsLink
    }
  },
  'badge': {
    meta: badgeMeta,
    stories: {
    'Playground': badge_Playground,
    'BadgeFilled': badge_BadgeFilled,
    'BadgeLight': badge_BadgeLight,
    'BadgeLighter': badge_BadgeLighter,
    'BadgeStroke': badge_BadgeStroke,
    'BadgeColors': badge_BadgeColors,
    'Size': badge_Size,
    'Square': badge_Square,
    'WithIcon': badge_WithIcon,
    'WithDot': badge_WithDot,
    'Disabled': badge_Disabled,
    'AsChild': badge_AsChild
    }
  },
  'banner': {
    meta: bannerMeta,
    stories: {
    'Playground': banner_Playground,
    'Error': banner_Error,
    'Warning': banner_Warning,
    'Success': banner_Success,
    'Information': banner_Information,
    'Feature': banner_Feature,
    'Primary': banner_Primary
    }
  },
  'button-group': {
    meta: buttonGroupMeta,
    stories: {
    'Playground': buttonGroup_Playground,
    'Default': buttonGroup_Default,
    'Sizes': buttonGroup_Sizes
    }
  },
  'button': {
    meta: buttonMeta,
    stories: {
    'Playground': button_Playground,
    'PrimaryVariant': button_PrimaryVariant,
    'NeutralVariant': button_NeutralVariant,
    'SuccessVariant': button_SuccessVariant,
    'WarningVariant': button_WarningVariant,
    'ErrorVariant': button_ErrorVariant,
    'Sizes': button_Sizes,
    'Disabled': button_Disabled,
    'WithIcon': button_WithIcon,
    'FullWidth': button_FullWidth,
    'AsChild': button_AsChild,
    'Composition': button_Composition
    }
  },
  'checkbox': {
    meta: checkboxMeta,
    stories: {
    'Playground': checkbox_Playground,
    'Demo': checkbox_Demo,
    'Variants': checkbox_Variants,
    'Disabled': checkbox_Disabled,
    'WithLabel': checkbox_WithLabel,
    'WithLabelExtended': checkbox_WithLabelExtended
    }
  },
  'color-picker': {
    meta: colorPickerMeta,
    stories: {
    'Playground': colorPicker_Playground,
    'Demo': colorPicker_Demo,
    'PopoverDemo': colorPicker_PopoverDemo
    }
  },
  'combo-box': {
    meta: comboBoxMeta,
    stories: {
    'Playground': comboBox_Playground,
    'Default': comboBox_Default,
    'WithPreselectedValues': comboBox_WithPreselectedValues,
    'Uncontrolled': comboBox_Uncontrolled,
    'FormSubmission': comboBox_FormSubmission,
    'Sizes': comboBox_Sizes,
    'SelectionConstraints': comboBox_SelectionConstraints,
    'TagVariants': comboBox_TagVariants,
    'States': comboBox_States,
    'Customization': comboBox_Customization,
    'WithIcons': comboBox_WithIcons
    }
  },
  'command-menu': {
    meta: commandMenuMeta,
    stories: {
    'Playground': commandMenu_Playground,
    'Demo': commandMenu_Demo
    }
  },
  'compact-button': {
    meta: compactButtonMeta,
    stories: {
    'Playground': compactButton_Playground,
    'Stroke': compactButton_Stroke,
    'Ghost': compactButton_Ghost,
    'White': compactButton_White,
    'Modifiable': compactButton_Modifiable,
    'Sizes': compactButton_Sizes,
    'FullRadius': compactButton_FullRadius,
    'Disabled': compactButton_Disabled,
    'AsChild': compactButton_AsChild
    }
  },
  'currency-input': {
    meta: currencyInputMeta,
    stories: {
    'Playground': currencyInput_Playground,
    'Default': currencyInput_Default,
    'Controlled': currencyInput_Controlled,
    'Sizes': currencyInput_Sizes,
    'ErrorState': currencyInput_ErrorState
    }
  },
  'datepicker': {
    meta: datepickerMeta,
    stories: {
    'Playground': datepicker_Playground,
    'Demo': datepicker_Demo,
    'PopoverDemo': datepicker_PopoverDemo,
    'ApprovalDemo': datepicker_ApprovalDemo,
    'RangeDemo': datepicker_RangeDemo
    }
  },
  'digit-input': {
    meta: digitInputMeta,
    stories: {
    'Playground': digitInput_Playground,
    'Demo': digitInput_Demo,
    'HasError': digitInput_HasError,
    'Disabled': digitInput_Disabled,
    'Square': digitInput_Square
    }
  },
  'divider': {
    meta: dividerMeta,
    stories: {
    'Playground': divider_Playground,
    'Line': divider_Line,
    'LineSpacing': divider_LineSpacing,
    'LineText': divider_LineText,
    'TextOnly': divider_TextOnly,
    'SolidText': divider_SolidText,
    'Content': divider_Content
    }
  },
  'dot-stepper': {
    meta: dotStepperMeta,
    stories: {
    'Playground': dotStepper_Playground,
    'Demo': dotStepper_Demo,
    'WithRadixTabs': dotStepper_WithRadixTabs
    }
  },
  'drawer': {
    meta: drawerMeta,
    stories: {
    'Playground': drawer_Playground,
    'Demo': drawer_Demo,
    'Basic': drawer_Basic
    }
  },
  'dropdown': {
    meta: dropdownMeta,
    stories: {
    'Playground': dropdown_Playground,
    'Demo': dropdown_Demo,
    'SubMenu': dropdown_SubMenu
    }
  },
  'emoji-dialog': {
    meta: emojiDialogMeta,
    stories: {
    'Playground': emojiDialog_Playground,
    'Default': emojiDialog_Default,
    'DeleteConfirmation': emojiDialog_DeleteConfirmation,
    'UnsavedChanges': emojiDialog_UnsavedChanges,
    'SuccessConfirmation': emojiDialog_SuccessConfirmation,
    'WithFormContent': emojiDialog_WithFormContent,
    'WithFloatingMemojis': emojiDialog_WithFloatingMemojis,
    'StaticNoAnimations': emojiDialog_StaticNoAnimations,
    'CustomEmojiArea': emojiDialog_CustomEmojiArea
    }
  },
  'fancy-button': {
    meta: fancyButtonMeta,
    stories: {
    'Playground': fancyButton_Playground,
    'Neutral': fancyButton_Neutral,
    'Primary': fancyButton_Primary,
    'Error': fancyButton_Error,
    'Basic': fancyButton_Basic,
    'WithIcon': fancyButton_WithIcon,
    'Sizes': fancyButton_Sizes,
    'Disabled': fancyButton_Disabled,
    'AsChild': fancyButton_AsChild
    }
  },
  'file-format-icon': {
    meta: fileFormatIconMeta,
    stories: {
    'Default': fileFormatIcon_Default,
    'Colors': fileFormatIcon_Colors,
    'Sizes': fileFormatIcon_Sizes
    }
  },
  'file-upload-card': {
    meta: fileUploadCardMeta,
    stories: {
    'Uploading': fileUploadCard_Uploading,
    'Failed': fileUploadCard_Failed,
    'CompletedDocument': fileUploadCard_CompletedDocument,
    'CompletedImage': fileUploadCard_CompletedImage,
    'CompletedVideo': fileUploadCard_CompletedVideo,
    'CompletedAudio': fileUploadCard_CompletedAudio,
    'CompactUploading': fileUploadCard_CompactUploading,
    'CompactCompleted': fileUploadCard_CompactCompleted,
    'CompactFailed': fileUploadCard_CompactFailed,
    'ItemUploading': fileUploadCard_ItemUploading,
    'ItemFailed': fileUploadCard_ItemFailed,
    'ItemCompletedDocument': fileUploadCard_ItemCompletedDocument,
    'ItemCompletedImage': fileUploadCard_ItemCompletedImage,
    'ItemCompactUploading': fileUploadCard_ItemCompactUploading,
    'ItemCompactCompleted': fileUploadCard_ItemCompactCompleted,
    'ItemCompactFailed': fileUploadCard_ItemCompactFailed
    }
  },
  'file-upload': {
    meta: fileUploadMeta,
    stories: {
    'Document': fileUpload_Document,
    'Image': fileUpload_Image,
    'Video': fileUpload_Video,
    'Audio': fileUpload_Audio,
    'Attachment': fileUpload_Attachment,
    'CustomOverrides': fileUpload_CustomOverrides,
    'Dragging': fileUpload_Dragging
    }
  },
  'form-field': {
    meta: formFieldMeta,
    stories: {
    'Playground': formField_Playground,
    'Demo': formField_Demo
    }
  },
  'hint': {
    meta: hintMeta,
    stories: {
    'Playground': hint_Playground,
    'Demo': hint_Demo,
    'Disabled': hint_Disabled,
    'HasError': hint_HasError
    }
  },
  'input': {
    meta: inputMeta,
    stories: {
    'Playground': input_Playground,
    'WithIcon': input_WithIcon,
    'Sizes': input_Sizes,
    'WithAffix': input_WithAffix,
    'WithInlineAffix': input_WithInlineAffix,
    'LabelAndHint': input_LabelAndHint,
    'WithKbd': input_WithKbd,
    'Password': input_Password,
    'PasswordWithLevel': input_PasswordWithLevel,
    'Disabled': input_Disabled,
    'ErrorState': input_ErrorState,
    'WithButton': input_WithButton,
    'WithTags': input_WithTags,
    'DateFieldStory': input_DateFieldStory,
    'PaymentInput': input_PaymentInput,
    'WithSelect': input_WithSelect,
    'WithInlineSelect': input_WithInlineSelect,
    'CounterInput': input_CounterInput,
    'Composition': input_Composition
    }
  },
  'kbd': {
    meta: kbdMeta,
    stories: {
    'Playground': kbd_Playground,
    'Demo': kbd_Demo
    }
  },
  'key-icon': {
    meta: keyIconMeta,
    stories: {
    'Playground': keyIcon_Playground,
    'Stroke': keyIcon_Stroke,
    'Lighter': keyIcon_Lighter,
    'Sizes': keyIcon_Sizes,
    'Colors': keyIcon_Colors
    }
  },
  'label': {
    meta: labelMeta,
    stories: {
    'Playground': label_Playground,
    'Demo': label_Demo
    }
  },
  'level-bar': {
    meta: levelBarMeta,
    stories: {
    'Playground': levelBar_Playground,
    'Levels': levelBar_Levels,
    'CustomSegments': levelBar_CustomSegments
    }
  },
  'link-button': {
    meta: linkButtonMeta,
    stories: {
    'Playground': linkButton_Playground,
    'Gray': linkButton_Gray,
    'Black': linkButton_Black,
    'Primary': linkButton_Primary,
    'Error': linkButton_Error,
    'Modifiable': linkButton_Modifiable,
    'Sizes': linkButton_Sizes,
    'Underline': linkButton_Underline,
    'WithIcon': linkButton_WithIcon,
    'Disabled': linkButton_Disabled,
    'AsChild': linkButton_AsChild
    }
  },
  'location-input': {
    meta: locationInputMeta,
    stories: {
    'Playground': locationInput_Playground,
    'Default': locationInput_Default
    }
  },
  'modal': {
    meta: modalMeta,
    stories: {
    'Playground': modal_Playground,
    'Demo': modal_Demo,
    'WithHeader': modal_WithHeader
    }
  },
  'pagination': {
    meta: paginationMeta,
    stories: {
    'Playground': pagination_Playground,
    'Demo': pagination_Demo,
    'Rounded': pagination_Rounded,
    'Group': pagination_Group,
    'AsLink': pagination_AsLink
    }
  },
  'password-input': {
    meta: passwordInputMeta,
    stories: {
    'Playground': passwordInput_Playground,
    'Default': passwordInput_Default,
    'WithStrength': passwordInput_WithStrength,
    'Sizes': passwordInput_Sizes,
    'ErrorState': passwordInput_ErrorState
    }
  },
  'phone-input': {
    meta: phoneInputMeta,
    stories: {
    'Playground': phoneInput_Playground,
    'Default': phoneInput_Default
    }
  },
  'popover': {
    meta: popoverMeta,
    stories: {
    'Playground': popover_Playground,
    'Demo': popover_Demo,
    'Position': popover_Position
    }
  },
  'progress-bar': {
    meta: progressBarMeta,
    stories: {
    'Playground': progressBar_Playground,
    'Color': progressBar_Color,
    'WithLabel': progressBar_WithLabel,
    'DataStorage': progressBar_DataStorage
    }
  },
  'progress-circle': {
    meta: progressCircleMeta,
    stories: {
    'Playground': progressCircle_Playground,
    'Default': progressCircle_Default
    }
  },
  'radio-card': {
    meta: radioCardMeta,
    stories: {
    'Playground': radioCard_Playground,
    'Default': radioCard_Default,
    'WithKeyIcons': radioCard_WithKeyIcons,
    'WithSimpleIcons': radioCard_WithSimpleIcons,
    'WithBadges': radioCard_WithBadges,
    'InlineDescription': radioCard_InlineDescription,
    'AllowDeselect': radioCard_AllowDeselect,
    'Disabled': radioCard_Disabled,
    'ErrorState': radioCard_ErrorState,
    'Composed': radioCard_Composed,
    'PrimaryVariant': radioCard_PrimaryVariant
    }
  },
  'radio': {
    meta: radioMeta,
    stories: {
    'Playground': radio_Playground,
    'Demo': radio_Demo,
    'Variants': radio_Variants,
    'Disabled': radio_Disabled,
    'WithLabel': radio_WithLabel,
    'WithLabelExtended': radio_WithLabelExtended
    }
  },
  'section-toggle': {
    meta: sectionToggleMeta,
    stories: {
    'Playground': sectionToggle_Playground,
    'Default': sectionToggle_Default,
    'Collapsed': sectionToggle_Collapsed,
    'Composed': sectionToggle_Composed
    }
  },
  'section': {
    meta: sectionMeta,
    stories: {
    'Playground': section_Playground,
    'Default': section_Default,
    'WithCustomHeaderWidth': section_WithCustomHeaderWidth,
    'Composed': section_Composed
    }
  },
  'select': {
    meta: selectMeta,
    stories: {
    'Playground': select_Playground,
    'Demo': select_Demo,
    'WithLabelHint': select_WithLabelHint,
    'WithIcons': select_WithIcons,
    'Sizes': select_Sizes,
    'WithCountryFlags': select_WithCountryFlags,
    'WithUsers': select_WithUsers,
    'Disabled': select_Disabled,
    'Compact': select_Compact,
    'CompactCountry': select_CompactCountry,
    'CompactSizes': select_CompactSizes,
    'InlineCountry': select_InlineCountry,
    'InputWithInlineSelect': select_InputWithInlineSelect,
    'WithInput': select_WithInput,
    'WithInputSizes': select_WithInputSizes
    }
  },
  'slider': {
    meta: sliderMeta,
    stories: {
    'Playground': slider_Playground,
    'Demo': slider_Demo,
    'Variants': slider_Variants,
    'Range': slider_Range,
    'WithTooltip': slider_WithTooltip
    }
  },
  'socials-input': {
    meta: socialsInputMeta,
    stories: {
    'Playground': socialsInput_Playground,
    'Default': socialsInput_Default
    }
  },
  'status-badge': {
    meta: statusBadgeMeta,
    stories: {
    'Playground': statusBadge_Playground,
    'Disabled': statusBadge_Disabled,
    'Completed': statusBadge_Completed,
    'Failed': statusBadge_Failed,
    'Pending': statusBadge_Pending,
    'AsChild': statusBadge_AsChild
    }
  },
  'switch': {
    meta: switchMeta,
    stories: {
    'Playground': switch_Playground,
    'Demo': switch_Demo,
    'Variants': switch_Variants,
    'Disabled': switch_Disabled,
    'WithLabel': switch_WithLabel,
    'WithLabelExtended': switch_WithLabelExtended
    }
  },
  'table': {
    meta: tableMeta,
    stories: {
    'Default': table_Default
    }
  },
  'tag-input': {
    meta: tagInputMeta,
    stories: {
    'Playground': tagInput_Playground,
    'Default': tagInput_Default,
    'Controlled': tagInput_Controlled,
    'MaxTags': tagInput_MaxTags,
    'GrayVariant': tagInput_GrayVariant,
    'Sizes': tagInput_Sizes
    }
  },
  'tag': {
    meta: tagMeta,
    stories: {
    'Playground': tag_Playground,
    'Stroke': tag_Stroke,
    'Gray': tag_Gray,
    'Rounded': tag_Rounded,
    'Disabled': tag_Disabled,
    'WithImage': tag_WithImage,
    'WithAvatar': tag_WithAvatar,
    'Dismissable': tag_Dismissable
    }
  },
  'textarea': {
    meta: textareaMeta,
    stories: {
    'Playground': textarea_Playground,
    'Demo': textarea_Demo,
    'InteractiveCounter': textarea_InteractiveCounter,
    'HasError': textarea_HasError,
    'WithLabelAndHint': textarea_WithLabelAndHint,
    'Disabled': textarea_Disabled,
    'Simple': textarea_Simple,
    'SimpleResize': textarea_SimpleResize
    }
  },
  'theme-provider': {
    meta: themeProviderMeta,
    stories: {
    'Default': themeProvider_Default,
    'Global': themeProvider_Global,
    'MultipleThemes': themeProvider_MultipleThemes
    }
  },
  'tooltip': {
    meta: tooltipMeta,
    stories: {
    'Playground': tooltip_Playground,
    'Light': tooltip_Light,
    'Size': tooltip_Size,
    'Position': tooltip_Position,
    'HTMLContent': tooltip_HTMLContent
    }
  },
  'upload-file-input': {
    meta: uploadFileInputMeta,
    stories: {
    'Playground': uploadFileInput_Playground,
    'Showcase': uploadFileInput_Showcase
    }
  }
};

export function getStory(componentName: string, storyName: string): (() => React.ReactNode) | null {
  const mod = storyRegistry[componentName];
  if (!mod) return null;
  const story = mod.stories[storyName];
  if (!story) return null;
  return typeof story === 'function' ? story : story.render ?? null;
}
