// Auto-generated by generate-story-registry.ts - do not edit
'use client';

import { default as badgeMeta, BadgeFilled as badge_BadgeFilled, BadgeLight as badge_BadgeLight, BadgeLighter as badge_BadgeLighter, BadgeStroke as badge_BadgeStroke, BadgeColors as badge_BadgeColors, Size as badge_Size, Square as badge_Square, WithIcon as badge_WithIcon, WithDot as badge_WithDot, Disabled as badge_Disabled, AsChild as badge_AsChild } from '@/components/ui/badge.stories';
import { default as buttonMeta, PrimaryVariant as button_PrimaryVariant, NeutralVariant as button_NeutralVariant, SuccessVariant as button_SuccessVariant, WarningVariant as button_WarningVariant, ErrorVariant as button_ErrorVariant, Sizes as button_Sizes, Disabled as button_Disabled, WithIcon as button_WithIcon, FullWidth as button_FullWidth, AsChild as button_AsChild } from '@/components/ui/button.stories';
import { default as calendarInputMeta, BasicUsage as calendarInput_BasicUsage } from '@/components/ui/calendar-input.stories';
import { default as circularProgressMeta, Default as circularProgress_Default, WithColorVariants as circularProgress_WithColorVariants } from '@/components/ui/circular-progress.stories';
import { default as currencyInputMeta, Default as currencyInput_Default } from '@/components/ui/currency-input.stories';
import { default as dividerMeta, Line as divider_Line, LineWithSpacing as divider_LineWithSpacing, LineWithText as divider_LineWithText, TextOnly as divider_TextOnly, SolidText as divider_SolidText, Content as divider_Content } from '@/components/ui/divider.stories';
import { default as inputMeta, Sizes as input_Sizes, Icons as input_Icons, Affixes as input_Affixes, States as input_States } from '@/components/ui/input.stories';
import { default as locationInputMeta, Default as locationInput_Default } from '@/components/ui/location-input.stories';
import { default as phoneInputMeta, Default as phoneInput_Default } from '@/components/ui/phone-input.stories';
import { default as popoverMeta, Default as popover_Default, InlinePortal as popover_InlinePortal } from '@/components/ui/popover.stories';
import { default as progressBarMeta, Default as progressBar_Default, PrimaryVariant as progressBar_PrimaryVariant } from '@/components/ui/progress-bar.stories';
import { default as radioCardGroupMeta, BasicUsage as radioCardGroup_BasicUsage, WithoutDescriptions as radioCardGroup_WithoutDescriptions, WithIcons as radioCardGroup_WithIcons, WithBadges as radioCardGroup_WithBadges, AllowDeselect as radioCardGroup_AllowDeselect, Disabled as radioCardGroup_Disabled } from '@/components/ui/radio-card-group.stories';
import { default as searchableComboBoxMeta, Default as searchableComboBox_Default } from '@/components/ui/searchable-combo-box.stories';
import { default as selectMeta, Sizes as select_Sizes, Variants as select_Variants, SelectStates as select_SelectStates } from '@/components/ui/select.stories';
import { default as socialsInputMeta, Default as socialsInput_Default } from '@/components/ui/socials-input.stories';
import { default as tagMeta, Default as tag_Default, GrayVariant as tag_GrayVariant } from '@/components/ui/tag.stories';
import { default as textareaMeta, Default as textarea_Default, Disabled as textarea_Disabled, WithLabel as textarea_WithLabel, WithMaximumLength as textarea_WithMaximumLength } from '@/components/ui/textarea.stories';
import { default as uploadFileInputMeta, Showcase as uploadFileInput_Showcase } from '@/components/ui/upload-file-input.stories';

export const storyRegistry: Record<string, {
  meta: any;
  stories: Record<string, any>;
}> = {
  'badge': {
    meta: badgeMeta,
    stories: {
    'BadgeFilled': badge_BadgeFilled,
    'BadgeLight': badge_BadgeLight,
    'BadgeLighter': badge_BadgeLighter,
    'BadgeStroke': badge_BadgeStroke,
    'BadgeColors': badge_BadgeColors,
    'Size': badge_Size,
    'Square': badge_Square,
    'WithIcon': badge_WithIcon,
    'WithDot': badge_WithDot,
    'Disabled': badge_Disabled,
    'AsChild': badge_AsChild
    }
  },
  'button': {
    meta: buttonMeta,
    stories: {
    'PrimaryVariant': button_PrimaryVariant,
    'NeutralVariant': button_NeutralVariant,
    'SuccessVariant': button_SuccessVariant,
    'WarningVariant': button_WarningVariant,
    'ErrorVariant': button_ErrorVariant,
    'Sizes': button_Sizes,
    'Disabled': button_Disabled,
    'WithIcon': button_WithIcon,
    'FullWidth': button_FullWidth,
    'AsChild': button_AsChild
    }
  },
  'calendar-input': {
    meta: calendarInputMeta,
    stories: {
    'BasicUsage': calendarInput_BasicUsage
    }
  },
  'circular-progress': {
    meta: circularProgressMeta,
    stories: {
    'Default': circularProgress_Default,
    'WithColorVariants': circularProgress_WithColorVariants
    }
  },
  'currency-input': {
    meta: currencyInputMeta,
    stories: {
    'Default': currencyInput_Default
    }
  },
  'divider': {
    meta: dividerMeta,
    stories: {
    'Line': divider_Line,
    'LineWithSpacing': divider_LineWithSpacing,
    'LineWithText': divider_LineWithText,
    'TextOnly': divider_TextOnly,
    'SolidText': divider_SolidText,
    'Content': divider_Content
    }
  },
  'input': {
    meta: inputMeta,
    stories: {
    'Sizes': input_Sizes,
    'Icons': input_Icons,
    'Affixes': input_Affixes,
    'States': input_States
    }
  },
  'location-input': {
    meta: locationInputMeta,
    stories: {
    'Default': locationInput_Default
    }
  },
  'phone-input': {
    meta: phoneInputMeta,
    stories: {
    'Default': phoneInput_Default
    }
  },
  'popover': {
    meta: popoverMeta,
    stories: {
    'Default': popover_Default,
    'InlinePortal': popover_InlinePortal
    }
  },
  'progress-bar': {
    meta: progressBarMeta,
    stories: {
    'Default': progressBar_Default,
    'PrimaryVariant': progressBar_PrimaryVariant
    }
  },
  'radio-card-group': {
    meta: radioCardGroupMeta,
    stories: {
    'BasicUsage': radioCardGroup_BasicUsage,
    'WithoutDescriptions': radioCardGroup_WithoutDescriptions,
    'WithIcons': radioCardGroup_WithIcons,
    'WithBadges': radioCardGroup_WithBadges,
    'AllowDeselect': radioCardGroup_AllowDeselect,
    'Disabled': radioCardGroup_Disabled
    }
  },
  'searchable-combo-box': {
    meta: searchableComboBoxMeta,
    stories: {
    'Default': searchableComboBox_Default
    }
  },
  'select': {
    meta: selectMeta,
    stories: {
    'Sizes': select_Sizes,
    'Variants': select_Variants,
    'SelectStates': select_SelectStates
    }
  },
  'socials-input': {
    meta: socialsInputMeta,
    stories: {
    'Default': socialsInput_Default
    }
  },
  'tag': {
    meta: tagMeta,
    stories: {
    'Default': tag_Default,
    'GrayVariant': tag_GrayVariant
    }
  },
  'textarea': {
    meta: textareaMeta,
    stories: {
    'Default': textarea_Default,
    'Disabled': textarea_Disabled,
    'WithLabel': textarea_WithLabel,
    'WithMaximumLength': textarea_WithMaximumLength
    }
  },
  'upload-file-input': {
    meta: uploadFileInputMeta,
    stories: {
    'Showcase': uploadFileInput_Showcase
    }
  }
};

export function getStory(componentName: string, storyName: string): (() => React.ReactNode) | null {
  const mod = storyRegistry[componentName];
  if (!mod) return null;
  const story = mod.stories[storyName];
  if (!story) return null;
  return typeof story === 'function' ? story : story.render ?? null;
}
